### ISSUE TITLE
bsvpreprocess.py hits AssertionError if backticks used in block comment

### ISSUE THREAD

**Issue by acw1251** [cambridgehackers/connectal#142]
I've started auto-generating documentation by parsing bsv files, and one of my conventions is causing bsvpreprocess.py to hit an AssertionError when  preprocessing some files.

The issue comes from having backticks (`` ` ``)  in comment blocks (``/*  ...  */``) like this: https://github.com/csail-csg/recycle-bsv-lib/blob/master/src/bsv/PrintTrace.bsv#L36

(In case you are curious, the generated documentation for this file is here: https://github.com/csail-csg/recycle-bsv-lib/blob/master/doc/markdown/PrintTrace.md)

I think this can be fixed by either completely ignoring comment blocks (maybe around here: https://github.com/cambridgehackers/connectal/blob/master/scripts/bsvpreprocess.py#L55) or by adding block comments to the `comment` variable instead of the `noncomment` variable.

**Comment by jameyhicks** [comment]
I think comment blocks should go in the comment variable, although I have not looked at the code in a while.

You're using markdown for the documentation? Could I convince you to use sphinx instead? It's not handled rendered directly by github, but we could run a travis job to build the documentation and publish it.

**Comment by hanw** [comment]
For markdown, I recently found out a nice tool called madoko that can generate html, pdf, tex all from a markdown file. (developed by MSR)

https://www.madoko.net/
https://www.npmjs.com/package/madoko

**Comment by jameyhicks** [comment]
But does it index and cross reference BSV types, modules, interfaces,
methods? sphinx does that and generates html, pdf, tex, epub, ...

**Comment by jameyhicks** [comment]
I don't have that much documentation, so I'm happy to change formats but I
do not want to lose functionality.

**Comment by hanw** [comment]
It only takes markdown as input files, and it is more suitable for writing documents, instead of generating documentation. It's better to stay with sphinx in this case.

**Comment by acw1251** [comment]
I'm using markdown for now because Github will render it for you (including BSV syntax highlighting). Eventually it would be nice to have documentation that doesn't require browsing through Github, so I'll look at sphinx and madoko for future use. Even if I choose to stay with markdown, it shouldn't be hard to make a sphinx output for the documentation generation script.

I added the line
```
source = re.sub(re.compile(r"/\*.*?\*/", re.MULTILINE | re.DOTALL), "", source)
```
just before [this line](https://github.com/cambridgehackers/connectal/blob/master/scripts/bsvpreprocess.py#L55) to strip out block comments, and compilation works again. I'll try adding block comments to the comment variable now.

If bsvpreprocess.py is just used for preprocessing the file, you can use the -E flag in bsc to do that. It adds `` `line `` statements to mark which file the lines come from.

**Comment by hanw** [comment]
This may be a dumb question, probably should asked earlier. But why do we need to write a preprocess script? Is the `bsc -E` preprocessing not sufficient?

**Comment by hanw** [comment]
oops, didn't read andy's reply in full. =P

**Comment by acw1251** [comment]
I added the workaround on the csail-csg fork so the riscy processors could compile again. It's not optimal, but it works for now.

**Comment by jameyhicks** [comment]
I pushed a change to bsvpreprocess to handle /* */ comments. Does it help?

**Comment by acw1251** [comment]
I still have the problem, but a small fix for multiline block comments fixes it. The fix is in PR #143

**Comment by acw1251** [comment]
This is all fixed now from PR #143

**Comment by jameyhicks** [comment]
yay!
